name: social-media-app
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-server
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data


  social-graph-db:
    image: postgres:16
    container_name: social-graph-db
    environment:
      POSTGRES_DB: management_booking_social_media_social_graph
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sistemas-2020
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
    ports:
      - "5433:5432"
    volumes:
      - social_graph_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d management_booking_social_media_social_graph" ]
      interval: 10s
      timeout: 5s
      retries: 10

  user-profile-db:
    image: postgres:16
    container_name: user-profile-db
    environment:
      POSTGRES_DB: management_booking_social_media_user_profile
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sistemas-2020
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
    ports:
      - "5434:5432"
    volumes:
      - user_profile_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d management_booking_social_media_user_profile" ]
      interval: 10s
      timeout: 5s
      retries: 10

  app-notification-db:
    image: postgres:16
    container_name: app-notification-db
    environment:
      POSTGRES_DB: management_booking_social_media_app_notification
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sistemas-2020
    command: >
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
    ports:
      - "5435:5432"
    volumes:
      - app_notification_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d management_booking_social_media_app_notification" ]
      interval: 10s
      timeout: 5s
      retries: 10

  microservice-social-graph:
    build:
      context: .
      dockerfile: apps/microservice-social-graph/Dockerfile
    container_name: microservice-social-graph
    depends_on:
      social-graph-db:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    ports:
      - "8090:8090"
    volumes:
      - ./apps/microservice-social-graph/src/main/resources/.env.docker:/.env:ro

  microservice-user-profile:
    build:
      context: .
      dockerfile: apps/microservice-user-profile/Dockerfile
    container_name: microservice-user-profile
    depends_on:
      user-profile-db:
        condition: service_healthy
    ports:
      - "8091:8090"
    volumes:
      - ./apps/microservice-user-profile/src/main/resources/.env.docker:/.env:ro

  microservice-app-notification:
    build:
      context: .
      dockerfile: apps/microservice-app-notification/Dockerfile
    container_name: microservice-app-notification
    depends_on:
      app-notification-db:
        condition: service_healthy
    ports:
      - "8092:8090"
    volumes:
      - ./apps/microservice-app-notification/src/main/resources/.env.docker:/.env:ro

  connect:
    image: debezium/connect:2.5
    container_name: debezium-connector-server
    depends_on:
      - kafka
      - social-graph-db
      - user-profile-db
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses

volumes:
  social_graph_db_data:
  user_profile_db_data:
  app_notification_db_data:
  elasticsearch_data: